 prowjob_namespace: default
 pod_namespace: test-pods
 periodics:
 - interval: 10m
   agent: kubernetes
   name: echo-test
   spec:
     containers:
     - image: alpine
       command: ["/bin/date"]
