apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prow-dev
  region: ap-southeast-2

managedNodeGroups:
  - name: prow-managed
    labels: { role: prow }
    instanceType: m5d.24xlarge
#    ScalingConfig:
#      minSize: 2
#      maxSize: 4
#      desiredCapacity: 2
    volumeSize: 200
    ssh:
      # publicKeyPath: ~/.ssh/OTHER.pub
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        albIngress: true
        cloudWatch: true
