apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prow
spec:
  chart:
    git: https://github.com/cncf-infra/prow-config
    path: charts/prow
    ref: 8e300fc
  releaseName: prow
  values:
    restartAllDeploymentsOnChange: true
    podNamespace: prow-workloads
    githubFromSecretRef:
      enabled: true
      oauth:
        name: prow-github-oauth
      hmac:
        name: prow-github-hmac
      cookie:
        name: prow-github-cookie
      oauthConfig:
        name: prow-github-oauth-config

    ingress:
      certmanager:
        enabled: false
      hosts:
        - host: prow.${SHARINGIO_PAIR_BASE_DNS_NAME}
      tls:
        - secretName: letsencrypt-prod
          hosts:
            - prow.${SHARINGIO_PAIR_BASE_DNS_NAME}

    configFromConfigMap:
      enabled: true
      name: prow-config

    pluginsFromConfigMap:
      enabled: true
      name: prow-plugins
