apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prow-${SHARINGIO_PAIR_NAME}
spec:
  chart:
    git: https://github.com/cncf-infra/prow-config
    path: charts/prow
    ref: 0819a4599ff311f3916be7ba6d3b4a6fe42d3e93
  releaseName: prow-${SHARINGIO_PAIR_NAME}
  values:
    podNamespace: prow-${SHARINGIO_PAIR_NAME}-workloads
    githubFromSecretRef:
      enabled: true
      oauth:
        name: prow-github-oauth
      hmac:
        name: prow-github-hmac
      cookie:
        name: prow-github-cookie
      oauthConfig:
        name: prow-github-oauth-config

    ingress:
      certmanager:
        enabled: false
      hosts:
        - host: prow.${SHARINGIO_PAIR_BASE_DNS_NAME}
      tls:
        - secretName: letsencrypt-prod
          hosts:
            - prow.${SHARINGIO_PAIR_BASE_DNS_NAME}

    configFromConfigMap:
      enabled: true
      name: prow-config

    pluginsFromConfigMap:
      enabled: true
      name: prow-plugins

