apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prow-${SHARINGIO_PAIR_NAME}
spec:
  chart:
    git: https://github.com/cncf-infra/prow-config
    path: charts/prow
    ref: 534b1803abffae0d2dbafd445a2540cc38639e64
  releaseName: prow-${SHARINGIO_PAIR_NAME}
  values:
    podNamespace: prow-${SHARINGIO_PAIR_NAME}-workloads
    githubFromSecretRef:
      enabled: true
      oauth:
        name: prow-github-oauth
      hmac:
        name: prow-github-hmac
      cookie:
        name: prow-github-cookie

    ingress:
      certmanager:
        enabled: false
      hosts:
        - host: prow.${SHARINGIO_PAIR_BASE_DNS_NAME}
      tls:
        - secretName: letsencrypt-prod
          hosts:
            - prow.${SHARINGIO_PAIR_BASE_DNS_NAME}

    configFromConfigMap:
      enabled: true
      name: prow-config

    pluginsFromConfigMap:
      enabled: true
      name: prow-plugins
    plugins:
      # config-updater
      # update prow cluster's configmaps from the repo with this plugin enabled; assumed to be a single repo
      # config_updater:
      #   maps:
      #     config.yaml:
      #       name: config
      #     plugins.yaml:
      #       name: plugins
      #     jobs/**/*.yaml:
      #       name: job-config

      # which plugins should be enabled for which orgs or org/repos
        ${SHARINGIO_PAIR_USER}/prow-config:
          plugins:
            # - approve
            - assign
            #- cat
            #- dog
            - hold
            - label
            - lgtm
            # - owners-label
            - shrug
            - size
            - skip
            - trigger
            - wip
            # - verify-owners
            - yuks
            - trigger
            - pony
            - cat
            - dog
            - goose

