prowjob_namespace: prow-${SHARINGIO_PAIR_NAME}
pod_namespace: prow-${SHARINGIO_PAIR_NAME}-workloads
managed_webhooks:
  respect_legacy_global_token: true
  org_repo_config:
    ${SHARINGIO_PAIR_NAME}/prow-config:
      token_created_after: 2020-06-24T00:10:00Z
in_repo_config:
  enabled:
    '*': true
deck:
  spyglass:
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
      - lens:
          config:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - .*/junit.*\.xml
      - lens:
          name: podinfo
        required_files:
          - podinfo.json
plank:
  job_url_template: |
    {{if .Spec.Refs}}
      {{if eq .Spec.Refs.Org "kubernetes-security"}}https://console.cloud.google.com/storage/browser/kubernetes-security-prow/{{else}}https://prow.${SHARINGIO_PAIR_BASE_DNS_NAME}/view/gcs/kubernetes-jenkins/{{end}}
    {{else}}https://prow.${SHARINGIO_PAIR_BASE_DNS_NAME}/view/gcs/kubernetes-jenkins/{{end}}
    {{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}
    {{if .Spec.Refs}}
      {{if ne .Spec.Refs.Org ""}}{{if ne .Spec.Refs.Org "kubernetes"}}/{{if and (eq .Spec.Refs.Org "kubernetes-sigs") (ne .Spec.Refs.Repo "poseidon")}}sigs.k8s.io{{else}}{{.Spec.Refs.Org}}{{end}}_{{.Spec.Refs.Repo}}{{else if ne .Spec.Refs.Repo "kubernetes"}}/{{.Spec.Refs.Repo}}{{end}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/
  report_templates:
    '*': '[Full PR test history](https://prow.${SHARINGIO_PAIR_BASE_DNS_NAME}/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://prow.${SHARINGIO_PAIR_BASE_DNS_NAME}/pr?query=is:pr+state:open+author:{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).'
  job_url_prefix_config:
    '*': https://prow.${SHARINGIO_PAIR_BASE_DNS_NAME}/view/
  default_decoration_configs:
    '*':
      gcs_configuration:
        bucket: s3://prow-logs
        path_strategy: explicit
      # secret must be set to RELEASE_NAME-s3-credentials
      s3_credentials_secret: prow-${SHARINGIO_PAIR_NAME}-s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20201019-3b28521b87
        entrypoint: gcr.io/k8s-prow/entrypoint:v20201019-3b28521b87
        initupload: gcr.io/k8s-prow/initupload:v20201019-3b28521b87
        sidecar: gcr.io/k8s-prow/sidecar:v20201019-3b28521b87
decorate_all_jobs: true
periodics:
  - interval: 1m
    agent: kubernetes
    name: echo-test
    decorate: true
    spec:
      containers:
        - image: alpine
          command:
            - /bin/date
