apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prow.fullname" . }}-config
  labels:
    {{- include "prow.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}
