{{- if .Values.hook.setupJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "prow.fullname" . }}-hook-setup
  labels:
    {{- include "prow.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.hook.setupJob.ttlSecondsAfterFinished | default 200 }}
      backoffLimit: {{ .Values.hook.setupJob.backoffLimit | default 50 }}
      backoffLimit: 4
      template:
        {{- include "prow.hook-setup" . | nindent 8 }}
{{- end }}
