apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prow.fullname" . }}-crier
  labels:
    app.kubernetes.io/component: crier
    {{- include "prow.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    checksum/secret-github-token: {{ include (print $.Template.BasePath "/secret-github-token.yaml") . | sha256sum }}
    checksum/secret-s3: {{ include (print $.Template.BasePath "/secret-s3-credentials.yaml") . | sha256sum }}
    checksum/secret-s3-test-pods: {{ include (print $.Template.BasePath "/secret-s3-credentials-test-pods.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.crier.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: crier
      {{- include "prow.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.crier.deploymentStrategy | nindent 4 }}
  template:
    metadata:
    {{- with .Values.crier.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/component: crier
        {{- include "prow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prow.fullname" . }}-crier
      terminationGracePeriodSeconds: {{ .Values.crier.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.crier.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-crier
          securityContext:
            {{- toYaml .Values.crier.securityContext | nindent 12 }}
          image: "{{ .Values.crier.image.repository }}:{{ .Values.crier.image.tag | default .Chart.AppVersion }}"
          args:
            - --github-endpoint=http://ghproxy.{{ .Release.Namespace }}
            {{- toYaml .Values.crier.args | nindent 12 }}
          imagePullPolicy: {{ .Values.crier.image.pullPolicy }}
          volumeMounts:
            - name: github-secrets-token
              mountPath: /etc/github/oauth
              subPath: oauth
              readOnly: true
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: s3-credentials
              mountPath: /etc/s3-credentials
              readOnly: true
          resources:
            {{- toYaml .Values.crier.resources | nindent 12 }}
      {{- with .Values.crier.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crier.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crier.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- include "prow.github-token.volume" . | nindent 6 }}
      {{- include "prow.configmap.volume" . | nindent 6 }}
      {{- include "prow.plugins.volume" . | nindent 6 }}
      - name: s3-credentials
        secret:
          secretName: {{ include "prow.fullname" . }}-s3-credentials
