apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prow.fullname" . }}-plugins
  labels:
    {{- include "prow.labels" . | nindent 4 }}
data:
  plugins.yaml: |
    {{ toYaml .Values.plugins | nindent 4 }}
