kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow.fullname" . }}-sinker
  labels:
    {{- include "prow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - delete
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - prow-sinker-leaderlock
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
