{{- if .Values.hook.setupJob.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow.fullname" . }}-hook-setupjob
  labels:
    {{- include "prow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
{{- end }}
