{{- if .Values.hook.setupJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prow.fullname" . }}-hook-setupjob
  labels:
    {{- include "prow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prow.fullname" . }}-hook-setupjob
subjects:
- kind: ServiceAccount
  name: {{ include "prow.fullname" . }}-hook-setupjob
  namespace: {{ .Release.Namespace }}
{{- end }}
