kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "prow.fullname" . }}-sinker
  {{- if .Values.podNamespace }}
  namespace: {{ .Values.podNamespace }}
  {{- else }}
  namespace: {{ .Values.config.pod_namespace }}
  {{- end }}
  labels:
    {{- include "prow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - get
      - patch
