kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow.fullname" . }}-crier
  labels:
    {{- include "prow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      - patch
