kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prow.fullname" . }}-deck
  {{- if .Values.podNamespace }}
  namespace: {{ .Values.podNamespace }}
  {{- else }}
  namespace: {{ .Values.config.pod_namespace }}
  {{- end }}
  labels:
    {{- include "prow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
