apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prow.fullname" . }}-plank-test-pods
  {{- if .Values.podNamespace }}
  namespace: {{ .Values.podNamespace }}
  {{- else }}
  namespace: {{ .Values.config.pod_namespace }}
  {{- end }}
  labels:
    {{- include "prow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prow.fullname" . }}-plank-test-pods
subjects:
- kind: ServiceAccount
  name: {{ include "prow.fullname" . }}-plank
  namespace: {{ .Release.Namespace }}
