{{- if not .Values.githubFromSecretRef.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prow.fullname" . }}-github-secrets-cookie
  labels:
    {{- include "prow.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.github.cookie | default "prowprowprowprow" | toString | b64enc }}
{{- end }}
