apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prow.fullname" . }}-s3-credentials
  namespace: {{ .Values.config.pod_namespace }}
  labels:
    app: deck
    {{- include "prow.labels" . | nindent 4 }}
stringData:
  service-account.json: |
    {
      "region": {{ .Values.minio.regionName | toString | quote }},
      "access_key": {{ .Values.minio.accessKey | toString | quote }},
      "endpoint": "minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": {{ .Values.minio.secretKey | toString | quote }}
    }
