{{- if not .Values.githubFromSecretRef.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prow.fullname" . }}-github-secrets-hmac
  labels:
    {{- include "prow.labels" . | nindent 4 }}
type: Opaque
data:
  hmac: {{ .Values.github.hmac | toString | b64enc }}
{{- end }}
