{{- if not .Values.githubFromSecretRef.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prow.fullname" . }}-github-secrets-token
  labels:
    {{- include "prow.labels" . | nindent 4 }}
type: Opaque
data:
  oauth: {{ .Values.github.oauth | toString | b64enc }}
{{- end }}
