apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prow.fullname" . }}-s3-credentials
  {{- if .Values.podNamespace }}
  namespace: {{ .Values.podNamespace }}
  {{- else }}
  namespace: {{ .Values.config.pod_namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: deck
    {{- include "prow.labels" . | nindent 4 }}
stringData:
  service-account.json: |
    {
      "region": {{ .Values.minio.regionName | toString | quote }},
      "access_key": {{ .Values.minio.accessKey | toString | quote }},
      "endpoint": "{{ include "prow.fullname" . }}-minio.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.minio.service.port }}",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": {{ .Values.minio.secretKey | toString | quote }}
    }
