apiVersion: v1
kind: Service
metadata:
  name: {{ include "prow.fullname" . }}-deck
  labels:
    app.kubernetes.io/component: deck
    {{- include "prow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deck.service.type }}
  ports:
    - port: {{ .Values.deck.service.port }}
      targetPort: {{ .Values.deck.bindPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: deck
    {{- include "prow.selectorLabels" . | nindent 4 }}
