apiVersion: v1
kind: Service
metadata:
  name: {{ include "prow.fullname" . }}-tide
  labels:
    app.kubernetes.io/component: tide
    {{- include "prow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tide.service.type }}
  ports:
    - port: {{ .Values.tide.service.port }}
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: tide
    {{- include "prow.selectorLabels" . | nindent 4 }}
