apiVersion: v1
kind: Service
metadata:
  name: {{ include "prow.fullname" . }}-minio
  labels:
    app.kubernetes.io/component: minio
    {{- include "prow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: {{ .Values.minio.bindPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: minio
    {{- include "prow.selectorLabels" . | nindent 4 }}
