{{- if .Values.hook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prow.fullname" . }}-hook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: hook
    {{- include "prow.labels" . | nindent 4 }}
  {{- with .Values.hook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
