{{- if .Values.statusreconciler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prow.fullname" . }}-statusreconciler
  namespace: {{ .Release.Namespace }}
  labels:
    app: statusreconciler
    {{- include "prow.labels" . | nindent 4 }}
  {{- with .Values.statusreconciler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
