ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: prow.bb.sharing.io
      tls:
        - secretName: letsencrypt-prod-prow-cncf-io
          hosts:
            - prow.bb.sharing.io

plugins:
  # config-updater
  # update prow cluster's configmaps from the repo with this plugin enabled; assumed to be a single repo
  config_updater:
    maps:
      config.yaml:
        name: config
      plugins.yaml:
        name: plugins
      jobs/**/*.yaml:
        name: job-config

  # which plugins should be enabled for which orgs or org/repos
  plugins:
    cncf-infra:
      # - approve
      - assign
      #- cat
      #- dog
      - hold
      - label
      - lgtm
      # - owners-label
      - shrug
      - size
      - skip
      - trigger
      - wip
      # - verify-owners
      - yuks

  cncf-infra/prow-config:
    - config-updater
    - pony

  cncf-infra/k8s-conformance:
    - cat
    - dog
    # - verify-conformance-request
