apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: prow
spec:
  commonName: prow.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  dnsNames:
  - prow.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: distribution
spec:
  commonName: distribution.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  dnsNames:
  - distribution.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: registry-k8s-io-envoy
spec:
  commonName: envoy.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  dnsNames:
  - envoy.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  - envoy-admin.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  dnsNames:
  - artifactserver.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  - demo.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  - reveal-multiplex.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod
