apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: prow
spec:
  commonName: prow.ii-sandbox.bobymcbobs-sdfg.pair.sharing.io
  dnsNames:
  - prow.ii-sandbox.bobymcbobs-sdfg.pair.sharing.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-prod
