# Certificate + cluster issuer

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: ${GIT_AUTHOR_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        dnsNames:
        - prow.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - distribution.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - envoy.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - envoy-admin.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - artifacts.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - demo.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
        - reveal-multiplex.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}
