# DNS

apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wildcard.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}-pair-sharing-io
  namespace: powerdns
spec:
  endpoints:
  - dnsName: "*.ii-sandbox.${SHARINGIO_PAIR_BASE_DNS_NAME}"
    recordTTL: 60
    recordType: A
    targets:
    - ${LOAD_BALANCER_IP}
